name: smoothie_app
description: Teste para Dafiti.

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_mobx: ^2.2.0+2
  flutter_launcher_icons: ^0.13.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.3.0
  
flutter:
  uses-material-design: true


# flutter pub run flutter_launcher_icons:main -f flutter_launcher_icons*